spring:
  application:
    name: doctor-service
  data:
    mongodb:
      uri: ${MONGODB_URI}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${DOCTOR_SERVICE_PORT:8080}
  servlet:
    context-path: /doctor

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
